### ISSUE TITLE
Peanut Infection event starts with the wrong classes

### ISSUE THREAD

**Issue by Oyplap** [galaxy119/SCPSL-Gamemodes#5]
Hello,
When you are in the lobby and you have enabled the peanut infection event, the wrong classes are getting spawned:

What happens:
Guards, Scientists and class d spawn (also 173 no issue, infection works fine).

What (probably) should happen:
Only class d and scp 173 spawn

**Comment by galaxy119** [comment]
Addressed in 76968b7

**Comment by Oyplap** [comment]
pog
